### PR TITLE
Helm charts updates

### LINKED ISSUE #3: storageClass from values.yaml is not used
The value defined in values.yaml is never used. Should be used here: https://github.com/influenzanet/cluster-management/blob/1ebd2c26948f4bfa48074388e3edd3e1272d66e1/influenzanet-2.0/templates/persistantClaim.yaml#L7

### LINKED ISSUE #4: remove personal information from values.yaml
It's best if we don't keep any valid email in this example configuration, eg:
https://github.com/influenzanet/cluster-management/blob/1ebd2c26948f4bfa48074388e3edd3e1272d66e1/influenzanet-2.0/values.yaml#L16

### LINKED ISSUE #7: encode secret in helm chart instead of requiring to base64 encode each
secrets values could be provided as is in the values and base64 encoded by the helm chart instead of needing the do it manually each time

### PR DESCRIPTION
**Pull request by m-delfino**
Restructure helm charts.

- rename influenzanet-2.0 to influenzanet
- general updates for kubernetes 1.21 and above
- general refactoring
- modifications to ingress, storage and tls domains
- restructured mongodb configuration
- tidy up values.yaml
- relaxed study timers
- created new pluggable charts for:
  - mailgun webhooks
  - maintenance mode
  - users migration
- updated README.md
- added subcharts README.md

All these modifications have already been extensively tested on the currently deployed IT platform, should be fine to merge this.

fixes #3, fixes #4, fixes #7

Please take note of the following recent commits concerning the final configuration options in `values.yaml`:

https://github.com/influenzanet/cluster-management/pull/6/commits/05863c1b991264e1e9e8148ebdf6d3ec43e92205, https://github.com/influenzanet/cluster-management/pull/6/commits/93804de9cf981a9c6cfe1f4db27dd15bf7179ab0, https://github.com/influenzanet/cluster-management/pull/6/commits/76f240729cde4f62ab281ac85c45609fc5cd204d

### CODE REVIEW

**Comment by m-delfino** [comment]
Still one issue to be fixed: tls secret names must be unique for each ingress to avoid:

```
certificate resource is not owned by this ingress. refusing to update non-owned certificate resource for ingress
```

We should verify if we are using the `secretName` annotation correctly.

ref: https://github.com/cert-manager/cert-manager/issues/2271

ref:https://github.com/cert-manager/cert-manager/issues/2585

Also, we need to verify that `privateKeySecretRef ` is used correctly:

ref:https://github.com/cert-manager/cert-manager/issues/1751

**Comment by cturbelin** [comment]
Sounds good to me, everything is ok on my deployment after the update

**Comment by cturbelin** [comment]
The last push mix generic and specific modifications for dk, I'm not sure it's a good idea to merge it, the specific values for danemark should be in a values override, no ?

**Comment by gf-isi** [comment]
thanks for letting us know, I pushed to the wrong remote

Il lun 29 ago 2022, 11:48 Clément Turbelin ***@***.***> ha
scritto:

**Comment by m-delfino** [comment]
fixed with a couple of force push, sorry for the noise
no sensitive data was included in those comments anyway, just some values specific to dk

**Pull request merged**
